// S&P 500 주요 종목 데이터
export const sp500Stocks = [
  // 기술주
  {
    symbol: "AAPL",
    name: "Apple Inc.",
    nameKr: "애플",
    sector: "기술주",
    price: 185.23,
  },
  {
    symbol: "MSFT",
    name: "Microsoft Corporation",
    nameKr: "마이크로소프트",
    sector: "기술주",
    price: 378.45,
  },
  {
    symbol: "GOOGL",
    name: "Alphabet Inc. Class A",
    nameKr: "구글 A",
    sector: "기술주",
    price: 142.56,
  },
  {
    symbol: "GOOG",
    name: "Alphabet Inc. Class C",
    nameKr: "구글 C",
    sector: "기술주",
    price: 144.12,
  },
  {
    symbol: "AMZN",
    name: "Amazon.com Inc.",
    nameKr: "아마존",
    sector: "기술주",
    price: 178.92,
  },
  {
    symbol: "META",
    name: "Meta Platforms Inc.",
    nameKr: "메타",
    sector: "기술주",
    price: 484.03,
  },
  {
    symbol: "NVDA",
    name: "NVIDIA Corporation",
    nameKr: "엔비디아",
    sector: "기술주",
    price: 892.45,
  },
  {
    symbol: "TSLA",
    name: "Tesla Inc.",
    nameKr: "테슬라",
    sector: "전기차",
    price: 412.67,
  },
  {
    symbol: "AVGO",
    name: "Broadcom Inc.",
    nameKr: "브로드컴",
    sector: "기술주",
    price: 1234.56,
  },
  {
    symbol: "ORCL",
    name: "Oracle Corporation",
    nameKr: "오라클",
    sector: "기술주",
    price: 112.34,
  },
  {
    symbol: "ADBE",
    name: "Adobe Inc.",
    nameKr: "어도비",
    sector: "기술주",
    price: 567.89,
  },
  {
    symbol: "CRM",
    name: "Salesforce Inc.",
    nameKr: "세일즈포스",
    sector: "기술주",
    price: 289.45,
  },
  {
    symbol: "CSCO",
    name: "Cisco Systems Inc.",
    nameKr: "시스코",
    sector: "기술주",
    price: 56.78,
  },
  {
    symbol: "INTC",
    name: "Intel Corporation",
    nameKr: "인텔",
    sector: "기술주",
    price: 43.21,
  },
  {
    symbol: "AMD",
    name: "Advanced Micro Devices Inc.",
    nameKr: "AMD",
    sector: "기술주",
    price: 178.9,
  },
  {
    symbol: "QCOM",
    name: "QUALCOMM Incorporated",
    nameKr: "퀄컴",
    sector: "기술주",
    price: 167.23,
  },
  {
    symbol: "TXN",
    name: "Texas Instruments Inc.",
    nameKr: "텍사스인스트루먼트",
    sector: "기술주",
    price: 189.34,
  },
  {
    symbol: "NFLX",
    name: "Netflix Inc.",
    nameKr: "넷플릭스",
    sector: "기술주",
    price: 623.45,
  },

  // 헬스케어
  {
    symbol: "JNJ",
    name: "Johnson & Johnson",
    nameKr: "존슨앤존슨",
    sector: "헬스케어",
    price: 164.23,
  },
  {
    symbol: "UNH",
    name: "UnitedHealth Group Inc.",
    nameKr: "유나이티드헬스",
    sector: "헬스케어",
    price: 523.67,
  },
  {
    symbol: "PFE",
    name: "Pfizer Inc.",
    nameKr: "화이자",
    sector: "헬스케어",
    price: 28.45,
  },
  {
    symbol: "ABBV",
    name: "AbbVie Inc.",
    nameKr: "애브비",
    sector: "헬스케어",
    price: 172.34,
  },
  {
    symbol: "TMO",
    name: "Thermo Fisher Scientific Inc.",
    nameKr: "써모피셔",
    sector: "헬스케어",
    price: 567.89,
  },
  {
    symbol: "MRK",
    name: "Merck & Co. Inc.",
    nameKr: "머크",
    sector: "헬스케어",
    price: 125.67,
  },
  {
    symbol: "ABT",
    name: "Abbott Laboratories",
    nameKr: "애보트",
    sector: "헬스케어",
    price: 112.34,
  },
  {
    symbol: "DHR",
    name: "Danaher Corporation",
    nameKr: "다나허",
    sector: "헬스케어",
    price: 245.78,
  },
  {
    symbol: "LLY",
    name: "Eli Lilly and Company",
    nameKr: "일라이릴리",
    sector: "헬스케어",
    price: 789.12,
  },
  {
    symbol: "BMY",
    name: "Bristol-Myers Squibb Company",
    nameKr: "브리스톨마이어스",
    sector: "헬스케어",
    price: 54.32,
  },

  // 소비재
  {
    symbol: "KO",
    name: "The Coca-Cola Company",
    nameKr: "코카콜라",
    sector: "소비재",
    price: 63.45,
  },
  {
    symbol: "PEP",
    name: "PepsiCo Inc.",
    nameKr: "펩시",
    sector: "소비재",
    price: 178.9,
  },
  {
    symbol: "PG",
    name: "Procter & Gamble Co.",
    nameKr: "P&G",
    sector: "소비재",
    price: 165.43,
  },
  {
    symbol: "WMT",
    name: "Walmart Inc.",
    nameKr: "월마트",
    sector: "소비재",
    price: 167.89,
  },
  {
    symbol: "HD",
    name: "The Home Depot Inc.",
    nameKr: "홈디포",
    sector: "소비재",
    price: 389.45,
  },
  {
    symbol: "MCD",
    name: "McDonald's Corporation",
    nameKr: "맥도날드",
    sector: "소비재",
    price: 289.67,
  },
  {
    symbol: "NKE",
    name: "NIKE Inc.",
    nameKr: "나이키",
    sector: "소비재",
    price: 112.34,
  },
  {
    symbol: "SBUX",
    name: "Starbucks Corporation",
    nameKr: "스타벅스",
    sector: "소비재",
    price: 98.76,
  },
  {
    symbol: "COST",
    name: "Costco Wholesale Corporation",
    nameKr: "코스트코",
    sector: "소비재",
    price: 812.45,
  },
  {
    symbol: "TGT",
    name: "Target Corporation",
    nameKr: "타겟",
    sector: "소비재",
    price: 156.78,
  },

  // 금융
  {
    symbol: "JPM",
    name: "JPMorgan Chase & Co.",
    nameKr: "JP모건",
    sector: "금융",
    price: 189.34,
  },
  {
    symbol: "BAC",
    name: "Bank of America Corporation",
    nameKr: "뱅크오브아메리카",
    sector: "금융",
    price: 34.56,
  },
  {
    symbol: "WFC",
    name: "Wells Fargo & Company",
    nameKr: "웰스파고",
    sector: "금융",
    price: 56.78,
  },
  {
    symbol: "GS",
    name: "The Goldman Sachs Group Inc.",
    nameKr: "골드만삭스",
    sector: "금융",
    price: 423.45,
  },
  {
    symbol: "MS",
    name: "Morgan Stanley",
    nameKr: "모건스탠리",
    sector: "금융",
    price: 98.76,
  },
  {
    symbol: "BLK",
    name: "BlackRock Inc.",
    nameKr: "블랙록",
    sector: "금융",
    price: 823.45,
  },
  {
    symbol: "C",
    name: "Citigroup Inc.",
    nameKr: "씨티그룹",
    sector: "금융",
    price: 61.23,
  },
  {
    symbol: "AXP",
    name: "American Express Company",
    nameKr: "아메리칸익스프레스",
    sector: "금융",
    price: 234.56,
  },
  {
    symbol: "V",
    name: "Visa Inc.",
    nameKr: "비자",
    sector: "금융",
    price: 278.9,
  },
  {
    symbol: "MA",
    name: "Mastercard Incorporated",
    nameKr: "마스터카드",
    sector: "금융",
    price: 456.78,
  },

  // 에너지
  {
    symbol: "XOM",
    name: "Exxon Mobil Corporation",
    nameKr: "엑슨모빌",
    sector: "에너지",
    price: 112.34,
  },
  {
    symbol: "CVX",
    name: "Chevron Corporation",
    nameKr: "쉐브론",
    sector: "에너지",
    price: 156.78,
  },
  {
    symbol: "COP",
    name: "ConocoPhillips",
    nameKr: "코노코필립스",
    sector: "에너지",
    price: 123.45,
  },
  {
    symbol: "SLB",
    name: "Schlumberger Limited",
    nameKr: "슐럼버거",
    sector: "에너지",
    price: 54.32,
  },
  {
    symbol: "EOG",
    name: "EOG Resources Inc.",
    nameKr: "EOG리소스",
    sector: "에너지",
    price: 134.56,
  },

  // 통신
  {
    symbol: "T",
    name: "AT&T Inc.",
    nameKr: "AT&T",
    sector: "통신",
    price: 18.45,
  },
  {
    symbol: "VZ",
    name: "Verizon Communications Inc.",
    nameKr: "버라이즌",
    sector: "통신",
    price: 41.23,
  },
  {
    symbol: "TMUS",
    name: "T-Mobile US Inc.",
    nameKr: "T모바일",
    sector: "통신",
    price: 167.89,
  },
  {
    symbol: "DIS",
    name: "The Walt Disney Company",
    nameKr: "디즈니",
    sector: "통신",
    price: 112.34,
  },
  {
    symbol: "CMCSA",
    name: "Comcast Corporation",
    nameKr: "컴캐스트",
    sector: "통신",
    price: 43.21,
  },

  // 산업재
  {
    symbol: "BA",
    name: "The Boeing Company",
    nameKr: "보잉",
    sector: "산업재",
    price: 178.9,
  },
  {
    symbol: "CAT",
    name: "Caterpillar Inc.",
    nameKr: "캐터필러",
    sector: "산업재",
    price: 345.67,
  },
  {
    symbol: "GE",
    name: "General Electric Company",
    nameKr: "GE",
    sector: "산업재",
    price: 156.78,
  },
  {
    symbol: "MMM",
    name: "3M Company",
    nameKr: "3M",
    sector: "산업재",
    price: 89.45,
  },
  {
    symbol: "HON",
    name: "Honeywell International Inc.",
    nameKr: "허니웰",
    sector: "산업재",
    price: 234.56,
  },
  {
    symbol: "UPS",
    name: "United Parcel Service Inc.",
    nameKr: "UPS",
    sector: "산업재",
    price: 156.78,
  },
  {
    symbol: "RTX",
    name: "Raytheon Technologies Corporation",
    nameKr: "레이시온",
    sector: "산업재",
    price: 98.76,
  },
  {
    symbol: "LMT",
    name: "Lockheed Martin Corporation",
    nameKr: "록히드마틴",
    sector: "산업재",
    price: 467.89,
  },

  // 기타
  {
    symbol: "BRK.B",
    name: "Berkshire Hathaway Inc. Class B",
    nameKr: "버크셔해서웨이",
    sector: "금융",
    price: 412.34,
  },
  {
    symbol: "SPY",
    name: "SPDR S&P 500 ETF Trust",
    nameKr: "S&P500 ETF",
    sector: "ETF",
    price: 523.45,
  },
  {
    symbol: "QQQ",
    name: "Invesco QQQ Trust",
    nameKr: "나스닥100 ETF",
    sector: "ETF",
    price: 445.67,
  },
];

export function searchStocks(query: string) {
  const lowerQuery = query.toLowerCase().trim();
  if (!lowerQuery) return [];

  return sp500Stocks
    .filter(
      (stock) =>
        stock.symbol.toLowerCase().includes(lowerQuery) ||
        stock.name.toLowerCase().includes(lowerQuery) ||
        stock.nameKr.includes(query.trim()),
    )
    .slice(0, 10); // 최대 10개 결과만 반환
}
